models.py
from app import db
from datetime import datetime
import re


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    #CHPU
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__ (self, *args, **kwargs):
        super (Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

main.py
from app import app
import view
from app import db
from posts.blueprint import posts


app.register_blueprint(posts, url_prefix='/blog')


if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template

from models import Post
posts = Blueprint('posts', __name__, template_folder='templates')
@posts.route('/')
def index():
    # posts = Post.query.all()
    return render_template('posts/index.html')

@posts.route('/create')
def create_post():
    return render_template('posts/creation.html')

# @posts.route('/<slug>')
# def post_detail(slug):
#     post = Post.query.filter(Post.slug == slug).first()
#     return render_template('posts/post_detail.html', posts=posts)

posts/templates/posts/creation.html
{% extends 'base.html' %}
{% block headers %}
{% endblock %}
{% block content_title %}
    create post
{% endblock %}

{% block content %}
    <div class="create_form" style="text-align: center; background: aliceblue">
        <form method="post">
            title
            <br>
            <input/>
            <br>
            body
            <br>
            <textarea></textarea>
            <br>
            <button type="submit">create</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content_title %}
    posts
{% endblock %}


{% block content %}
    <a href = "{{ url_for('posts.create_post') }}"><button type="submit" style="padding: 5px; margin: 10px">create post</button></a>
    {% for post in posts %}
    <p>
{#        {{ url_for('posts.post_detail', slug = post.slug) }}#}
        <a href ="#">{{post.title }}</a>
    </p>
    {% endfor %}
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {{ post.body }}
{% endblock %}

templates/about.html
{% extends 'base.html' %}

{% block content_title %}
    Klyukina E.
    <br/>
    Yakovlev E.
{% endblock %}

{% block content %}
    <p>
        Thank you for attention!
    </p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block headers %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/base.css">
    <title>Title</title>
</head>
<body>
<div class="wrapper">
    <div class="header">
        <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Kate's blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link disabled" href="/">home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('sign_in') }}">sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('sign_up') }}">sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.index') }}">posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('about') }}">about</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="content">
        <h1>
            {% block content_title %}
            {% endblock %}
        </h1>
        {% block content %}
        {% endblock %}
    </div>

    <div class="footer">
        <!-- Footer -->
        <footer class="page-footer font-small indigo">
            <!-- Footer Links -->
            <div class="container">
                <hr class="rgba-white-light" style="margin: 0 15%;">
                <!-- Grid row-->
                <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
                    <!-- Grid column -->
                    <div class="col-md-8 col-12 mt-5">
                        <p style="line-height: 1.7rem">
                            Poems, lirics and texts... <br/>
                            all you want is here
                        </p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row-->
                <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
                <!-- Grid row-->
                <div class="row pb-3">
                    <!-- Grid column -->
                    <div class="col-md-12">
                        <div class="mb-5 text-center">
                            <!--VK-->
                            <a class="vk-ic" href="#">
                                <i class="fab fa-vk fa-lg white-text mr-4"> </i>
                            </a>
                            <!--Instagram-->
                            <a class="ins-ic" href="#">
                                <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
                            </a>
                        </div>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row-->
            </div>
            <!-- Footer Links -->
            <div class="footer-copyright text-center py-3">© 2019 Copyright:
                <a href="#"> Ekaterina Klyukina</a>
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content_title %}
    Hello, it is main page
{% endblock %}

{% block content %}
    Content is here must be!
{% endblock %}

templates/sign_in.html
{% extends 'base.html' %}

{% block content_title %}
    sign in
{% endblock %}

{% block content %}
    <form method="post" style="margin: 0 auto; text-align: center">
        <p>username</p>
        <input type="text"/>
        <br>
        <p>password</p>
        <input type="password"/>
        <br>
        <button type="submit">sign in</button>
    </form>
{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}

{% block content_title %}
    sign in
{% endblock %}

{% block content %}
    <form method="post" style="margin: 0 auto; text-align: center">
        <p>username</p>
        <input type="text"/>
        <br>
        <p>email</p>
        <input type="email"/>
        <br>
        <p>password</p>
        <input type="password"/>
        <br>
        <button type="submit" style="margin 10px">sign in</button>
    </form>
{% endblock %}